### ISSUE TITLE
Enable profiling of certain libraries

### ISSUE THREAD

**Issue by captain-yoshi** [stefanbesler/twingrind#10]
> If you are using PLC libraries you can reuse the hashmap file and enabling profiling for your libraries as well by a similar call to twingrind prepare.

Not sure how to enable profiling for my libraries.

I have my library _TcRobot_ and my task _TcRobotExamples_ and tried to do the following:
```bash
# prepare the task
 twingrind prepare -d /c/ws/TcRobot/TcRobotExample/TcRobotExample -m /c/ws/TcRobot/TcRobotExample/TcRobotExample/hashmap

# prepare the libray
 twingrind prepare -d /c/ws/TcRobot/TcRobot/TcRobot -m /c/ws/TcRobot/TcRobotExample/TcRobotExample/hashmap

# Not sure... Do I have to recompile my library ? Tried it and recompiled my task, but it gave multiple errors...

```

**Comment by beslst** [comment]
It works like this

- add the twingrind library to your library and your actual plc
- run the prepare command for the library and actual plc and use the **same hash map file**
- Save & install the library
- Activate the PLC


It is important to use the same hash map file for all of the libraries, which you want to profile, and your PLC.

**Comment by stefanbesler** [comment]
@captain-yoshi can I close this issue? it be working if you use the same hashmap file, right?

**Comment by captain-yoshi** [comment]
Yup it works as expected. Thanks again!
