### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by mriepl** [stefanbesler/twingrind#5]
Hi,

if you compile you plc programm with the compiler definition "TC_SYM_WITH_NAMESPACE" you cant get access to the symbol.
Because the Namspace of the Library will be added to the symbolname.

I would suggesst you to add an parameter for the symbol prefix,

Best Regards
Markus

**Comment by stefanbesler** [comment]
Did not know about this Compiler define, is this documented by Beckhoff somewhere?

I guess you mean I should add an argument for the process and fetch python scripts? If so, np, I can do that

**Comment by mriepl** [comment]
its not documented, but it adds the namespace to all symbols from libraries, thats it!
this is neccessary if you have in two different libraries the same symbol!

yes please add an argument for the process and fetch script!

**Comment by stefanbesler** [comment]
You should be able to overwrite the namespace of the profiler library by using the new `-N` argument. If not specified, pytwingrind tries to connect to the profiler via "Profiler" (no namespace) and fallsback to using the default namespace "Twingrind.Profiler".
I'll push a new release somewhen this week
