### ISSUE TITLE
Symbol not found for Profiler.Data

### ISSUE THREAD

**Issue by mriepl** [stefanbesler/twingrind#6]
https://github.com/stefanbesler/twingrind/blob/759669c64ce397d49bce641d9e8b298a72afd2dd/pytwingrind/pytwingrind/fetch.py#L49

Typo für symbolname "Profiler.Data[0,1]"! You have added an space (Hex 20) between the two array positions!
Please delete the space in [{frame},< >{task}]

if you have done this please release an new version, thx

**Comment by stefanbesler** [comment]
are you using Beckhoff's open source implementation of ADS? I don't have this issue with the proprietary one, removed the space though. I'll create a release once I implemented and tested the other issue you submitted
