### ISSUE TITLE
Pop/Push mismatch

### ISSUE THREAD

**Issue by captain-yoshi** [stefanbesler/twingrind#9]
I have a PLC project which relies on a custom library. When following the procedure, I get his error:

```bash
$ twingrind prepare -d /c/ws/TcRobot/TcRobotExample/TcRobotExample -m /c/ws/TcRobot/TcRobotExample/TcRobotExample/hashmap
INFO:root:Updating an existing hashfile
DEBUG:root:DEMO_SIC2: guards added in 1 methods, contains (3 returns)
```

![image](https://github.com/stefanbesler/twingrind/assets/32679594/83518c5f-49f8-433a-9d13-37808f0b3cde)

**Comment by beslst** [comment]
Do you have multiple tasks that run in parallel? If yes, this is no supported atm
Custom libraries should not be an issue, twingrind even supports adding profiling to multiple libraries, as long there is only 1 concurrent task and 1 PRG and only 1 call to Twingrind.Profiler()

**Comment by captain-yoshi** [comment]
Nope, only one task and one program. Here is what my program looks like after the prepare command:

```cpp
(* @@ PROFILER @@ *)Twingrind.Profiler.Push(1245984901);(* @@ PROFILER @@ *)
Twingrind.Profiler();

CASE ProgramState OF
    0:  // Wait one cycle, do noting
        ProgramState := 1;
    1:  // Initialization
        ....
    2:
        FOR JointNumber:=1 TO NUMBER_OF_JOINTS DO
            IF JointsConfigured[JointNumber] <> TRUE THEN
                (* @@ PROFILER @@ *)Twingrind.Profiler.Pop(1245984901); (* @@ PROFILER @@ *)RETURN;
            END_IF
        END_FOR

        ...

        // Break if not properly reconfigured
        FOR JointNumber:=1 TO NUMBER_OF_JOINTS DO
            IF JointsConfigured[JointNumber] <> TRUE THEN
                (* @@ PROFILER @@ *)Twingrind.Profiler.Pop(1245984901); (* @@ PROFILER @@ *)RETURN;
            END_IF
        END_FOR
END_CASE

(* @@ PROFILER @@ *)Twingrind.Profiler.Pop(1245984901);(* @@ PROFILER @@ *)
```
![image](https://github.com/stefanbesler/twingrind/assets/32679594/b805100d-1e6e-4134-bfc2-61918ca02847)

**Comment by beslst** [comment]
Please swap the first and second line so that Twingrind.Profiler(); is the first command and the Push command comes after it

```
Twingrind.Profiler();
(* @@ PROFILER @@ *)Twingrind.Profiler.Push(1245984901);(* @@ PROFILER @@ *)
```

I see that the readme is a misleading here, I usually run the prepare command and only then add the line  Twingrind.Profiler(); …  I’ll dhange the readme

**Comment by captain-yoshi** [comment]
Sweet ! It now works. Thanks for updating the README.
